export const departments = [
  "Computer Science and Engineering",
  "Electronics and Communication Engineering",
  "Electrical and Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Information Technology",
  "Chemical Engineering",
  "Biotechnology",
  "Physics",
  "Chemistry",
  "Mathematics",
  "English",
  "Management Studies",
  "Computer Applications",
  "Artificial Intelligence and Data Science",
  "Cyber Security",
  "Agricultural Engineering",
  "Automobile Engineering",
  "Aeronautical Engineering",
  "Biomedical Engineering",
  "Food Technology",
  "Textile Technology",
  "Environmental Engineering",
  "Robotics and Automation",
  "Mechatronics Engineering",
  "Mining Engineering",
  "Petroleum Engineering",
  "Aerospace Engineering",
  "Marine Engineering",
  "Industrial Engineering",
  "Production Engineering",
  "Metallurgical Engineering",
  "Material Science and Engineering",
  "Architecture",
  "Pharmacy",
  "Applied Sciences",
  "Humanities and Social Sciences",
  "Physical Education",
  "Library Science",
  "Other"
];