// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zwxrtpyizempbljmozbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eHJ0cHlpemVtcGJsam1vemJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDU2NDUsImV4cCI6MjA3MDIyMTY0NX0.6hJMYfV2896DcRDobVAZnmOPQfm9YdYT32rhhCzkgmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);